spring:
  application:
    name: order
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
      profile: test
    stream:
      bindings:
        myMessage:
          group: order
          content-type: application/json
  zipkin:
    base-url: http://zipkin:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: "jdbc:mysql://localhost:3306/SpringCloud_Sell?\
         useUnicode=true\
         &characterEncoding=UTF-8\
         &autoReconnect=true\
         &allowMultiQueries=true\
         &useSSL=false\
         &autoReconnect=true"
  redis:
    database: 0
    timeout: 10000
    pool:
      max-idle: 300 #空闲连接实例的最大数目，为负值时没有限制
      min-idle: 50 #空闲连接实例的最小数目，为负值时没有限制
      max-active: 1000 #可用连接实例的最大数目，为负值时没有限制
    cluster:
      nodes:
       - 192.168.43.30:8001
       - 192.168.43.30:8002
       - 192.168.43.30:8003
       - 192.168.43.30:8004
       - 192.168.43.30:8005
       - 192.168.43.30:8006
      connTimeOut: 1000 #连接server超时时间
      soTimeOut: 1000 #等待response超时时间
      maxAttempts: 2  #连接失败重试次数
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.openfeign: debug

server:
  port: 8091

env:
 test
