spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: "jdbc:mysql://localhost:3306/SpringCloud_Sell?\
         useUnicode=true\
         &characterEncoding=UTF-8\
         &autoReconnect=true\
         &allowMultiQueries=true\
         &useSSL=false\
         &autoReconnect=true"

server:
  port: 8091

env:
 dev5

